version: '3.8'

services:
  nginx:
    image: nginx:1.28.0-alpine-slim
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    expose:
      - "3000"
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
